# Generated by Django 2.2.7 on 2019-11-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True, verbose_name='Text of question')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(auto_now_add=True)),
                ('task_done', models.BooleanField()),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Recruit')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Question')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(verbose_name='Is this answer right')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Question')),
            ],
        ),
    ]
