# Generated by Django 2.2.7 on 2019-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_answers_question_quiz_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='version',
            field=models.TextField(default=1, verbose_name='Version of answer'),
            preserve_default=False,
        ),
    ]
