# Generated by Django 2.2.7 on 2019-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_answers_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(null=True),
        ),
    ]
