# Generated by Django 2.2.7 on 2019-11-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191123_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='sith',
            name='shadow_hand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Recruit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
