# Generated by Django 2.2.7 on 2019-12-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191130_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sith',
            name='shadow_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Recruit'),
        ),
    ]
