# Generated by Django 2.2.7 on 2019-12-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191201_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sith',
            name='shadow_hand',
        ),
        migrations.AddField(
            model_name='recruit',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Sith'),
        ),
    ]
